# LOG_LEVEL: str = "INFO"
LOG_LEVEL: str = "DEBUG"
http_exception: str = "400 EXCEPTION"
request_validation_exception: str = "422 EXCEPTION"
handled_internal_exception: str = "HANDLED EXCEPTION"
unexpected_exception: str = "UNEXPECTED EXCEPTION"
